# Generated by Django 5.2.9 on 2025-12-29 02:28

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('category', models.TextField()),
                ('author', models.TextField()),
                ('description', models.TextField()),
                ('cover_image', models.TextField()),
                ('file_url', models.TextField()),
                ('tags', models.JSONField(default=list)),
                ('downloads', models.IntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ebooks',
                'ordering': ['-downloads', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EbookCategory',
            fields=[
                ('_id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('slug', models.TextField(unique=True)),
                ('color', models.TextField()),
                ('icon', models.TextField()),
                ('ebooks_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelTable(
            name='message',
            table=None,
        ),
    ]
