# Generated by Django 6.0.1 on 2026-01-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='initial_emotion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
